name: Validate Prod Merge
on:
  pull_request:
    branches: [prod]


jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR is from stage
        run: |
          if [ "$GITHUB_BASE_REF" != "prod" ] || [ "GITHUB_HEAD_REF != "stage"]; then
            echo "PRs to prod must come from stage"
            exit 1
          fi
