name: Validate Stage Merge
on:
  pull_request:
    branches: [stage]


jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR is from devel
        run: |
          if [ "$GITHUB_BASE_REF" != "stage" ] ||  [ "GITHUB_HEAD_REF != "devel"]; then
            echo "PRs to stage must come from devel"
            exit 1
          if 
